spring.application.name=Ornek3

spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=ApplicationDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sam
spring.datasource.password=Araba

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
